### PR TITLE
Adds a TwigExtension to access flash messages within a Twig template

### PR DESCRIPTION
**Pull request by NigelGreenway**
I have added a `TwigExtension` to allow retrieval of either a single message [TwigExtension#getMessage](https://github.com/NigelGreenway/Slim-Flash/blob/twig-flash-extension/src/TwigExtension.php#L56) or a collection of all messages / specific group of messages [TwigExtension#getMessages](https://github.com/NigelGreenway/Slim-Flash/blob/twig-flash-extension/src/TwigExtension.php#L75).

### CODE REVIEW

**Comment by NigelGreenway** [comment]
Looking into the failure.

_(Was developing in php-7.0.0 env)_

**Comment by NigelGreenway** [comment]
I have just realised that I have not updated the keywords part of the composer file. Would you want me to add "twig" and "twig extension" to the array?

**Comment by geggleto** [comment]
We should not couple this project with the Twig-View.

If you want to extend functionality with Twig, you should create a bridge that requires both SlimFlash and TwigView

**Comment by chrisvanpatten** [comment]
This is really great. Would love to see this as a separate module so it can be used @NigelGreenway!

**Comment by NigelGreenway** [comment]
Hi @chrisvanpatten, thanks. I will get it sorted this weekend.

I completely forgot about it to be honest.

**Comment by NigelGreenway** [comment]
This is not ready to be merged yet.

I have extracted the code into it's own repo as per @geggleto's suggestion, but it needs setting up properly. The only change is to suggest my package. Not sure if this is the right thing to suggest?

**Comment by chrisvanpatten** [comment]
@nigelgreenway have you published a new standalone repository for the Twig extension? I can't seem to find it…

**Comment by NigelGreenway** [comment]
@chrisvanpatten I haven't yet, I have it written it but need to get it published. Wife's 30th this weekend so I have left the laptop closed.

Should get it done either tomorrow lunch or by Tuesday night. You in need of it?

**Comment by NigelGreenway** [comment]
Going to close this if agreed, as [this](https://github.com/kanellov/slim-twig-flash) has already solved the issue which is created by @kanellov.

Maybe add this as a suggested package as I was intending to do with a192eeea622ce16a60269cb98a57799917971114

Thoughts?

cc/ @geggleto

**Comment by akrabat** [comment]
Added a note to the README.

**Pull request closed without merging**
