### PR TITLE
Add throws docblock and clean code

### PR DESCRIPTION
**Pull request by designermonkey**

### CODE REVIEW

**Comment by codeguy** [comment]
This will need rebased as soon as we merge in @silentworks' PR first which removes the Pimple dependency stuff.

**Comment by designermonkey** [comment]
Throw me a shout when it's done and I'll jump on it.

**Comment by codeguy** [comment]
You're good to rebase now.

**Comment by designermonkey** [comment]
All done. I had to just fix a merge conflict, but it's all fine.

**Comment by silentworks** [comment]
Pimple use statements need to go please.

**Pull request merged**
